[package]
name = "livestream_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = "0.8.3"
reqwest = { version = "0.11.18", features = ["tokio-native-tls", "stream", "blocking"] }
scraper = "0.17.1"
tokio = { version = "1.32.0", features = ["full"] }
futures = "0.3.28"
regex = "1.9.3"
chrono = "0.4.26"
anyhow = "1.0.75"
once_cell = "1.18.0"
config = "0.10"
async-std = "1.10.0"
winapi = { version = "0.3", features = ["winuser"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
url = "2.2.2"
rand = "0.8.4"
lazy_static = "1.4"
toml = "0.5"