[package]
name = "ttautorecord"
version = "4.0.0"
edition = "2021"

[dependencies]
fantoccini = "0.19.3"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.107"
serde = "1.0"
cookie = "0.16"
